// Code generated by MockGen. DO NOT EDIT.
// Source: transfer_repository.go

// Package transferrepository is a generated GoMock package.
package transferrepository

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	transfer "github.com/codepnw/simple-bank/internal/features/transfer"
	gomock "github.com/golang/mock/gomock"
)

// MockTransferRepository is a mock of TransferRepository interface.
type MockTransferRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransferRepositoryMockRecorder
}

// MockTransferRepositoryMockRecorder is the mock recorder for MockTransferRepository.
type MockTransferRepositoryMockRecorder struct {
	mock *MockTransferRepository
}

// NewMockTransferRepository creates a new mock instance.
func NewMockTransferRepository(ctrl *gomock.Controller) *MockTransferRepository {
	mock := &MockTransferRepository{ctrl: ctrl}
	mock.recorder = &MockTransferRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransferRepository) EXPECT() *MockTransferRepositoryMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockTransferRepository) Insert(ctx context.Context, tx *sql.Tx, input *transfer.Transfer) (*transfer.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, tx, input)
	ret0, _ := ret[0].(*transfer.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockTransferRepositoryMockRecorder) Insert(ctx, tx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockTransferRepository)(nil).Insert), ctx, tx, input)
}
