// Code generated by MockGen. DO NOT EDIT.
// Source: entry_repository.go

// Package entryrepository is a generated GoMock package.
package entryrepository

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	entry "github.com/codepnw/simple-bank/internal/features/entry"
	gomock "github.com/golang/mock/gomock"
)

// MockEntryRepository is a mock of EntryRepository interface.
type MockEntryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEntryRepositoryMockRecorder
}

// MockEntryRepositoryMockRecorder is the mock recorder for MockEntryRepository.
type MockEntryRepositoryMockRecorder struct {
	mock *MockEntryRepository
}

// NewMockEntryRepository creates a new mock instance.
func NewMockEntryRepository(ctrl *gomock.Controller) *MockEntryRepository {
	mock := &MockEntryRepository{ctrl: ctrl}
	mock.recorder = &MockEntryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntryRepository) EXPECT() *MockEntryRepositoryMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockEntryRepository) Insert(ctx context.Context, tx *sql.Tx, input *entry.Entry) (*entry.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, tx, input)
	ret0, _ := ret[0].(*entry.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockEntryRepositoryMockRecorder) Insert(ctx, tx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockEntryRepository)(nil).Insert), ctx, tx, input)
}
